name: guided-diffusion
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=7_kmp_llvm
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - appdirs=1.4.4=pyhd8ed1ab_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - backports.zstd=1.3.0=py310h69bd2ac_0
  - brotli-python=1.2.0=py310hba01987_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.10.19=py310hd8ed1ab_2
  - debugpy=1.8.19=py310h8a20257_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - eval_type_backport=0.3.1=pyha770c72_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=hecca717_0
  - filelock=3.20.3=pyhd8ed1ab_0
  - freetype=2.14.1=ha770c72_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.46=pyhd8ed1ab_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310h63ebcad_2
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.11=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyha191276_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.15=h7f713cb_2
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h0aef613_1
  - libabseil=20230802.1=cxx17_h59595ed_0
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libcblas=3.11.0=5_h0358290_openblas
  - libdeflate=1.19=hd590300_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.3=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=h4751f2c_7
  - libhwloc=2.12.1=default_h3d81e11_1000
  - libjpeg-turbo=2.1.5.1=hd590300_1
  - liblapack=3.11.0=5_h47877c9_openblas
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libpng=1.6.54=h421ea60_0
  - libprotobuf=4.24.4=hf27288f_0
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.6.0=h29866fb_1
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.51.0=hb03c661_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.15=h0b41bf4_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=21.1.8=h4922eb0_0
  - markupsafe=3.0.3=py310h3406613_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mkl=2022.2.1=h6508926_16999
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - numpy=1.26.4=py310hb13e2d6_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=10.0.1=py310h29da1c1_1
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.1=py310h139afa4_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-core=2.41.5=py310hd8f68c5_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.18=h1a3bd86_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=2_cp310
  - pytorch=2.0.0=cpu_mkl_py310h6d3c8b7_104
  - pyyaml=6.0.3=py310h3406613_0
  - pyzmq=27.1.0=py310h4f33d48_0
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=pyhcf101f3_1
  - sentry-sdk=2.49.0=pyhd8ed1ab_0
  - setproctitle=1.3.7=py310h139afa4_0
  - setuptools=80.9.0=py310h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=ha0421bc_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - sqlite=3.51.1=he0a8d7e_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2021.13.0=h8d10470_4
  - tk=8.6.14=h39e8969_0
  - torchvision=0.15.1=cpu_py310h0397dac_0
  - tornado=6.5.4=py310ha78b2d2_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing=3.10.0.0=pyhd8ed1ab_2
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.6.3=pyhd8ed1ab_0
  - wandb=0.23.1=py310h4a20303_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libpthread-stubs=0.3=1
  - xorg-libx11=1.6.4=0
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcb=1.12=3
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h280c20c_3
  - zeromq=4.3.5=h387f397_9
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - absl-py==2.3.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - diffusers==0.11.1
      - egl-probe==1.0.2
      - etils==1.13.0
      - evdev==1.9.2
      - fonttools==4.61.1
      - fsspec==2026.1.0
      - glfw==2.10.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - huggingface-hub==0.23.4
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.1
      - importlib-resources==6.5.2
      - iniconfig==2.3.0
      - kiwisolver==1.4.9
      - llvmlite==0.46.0
      - markdown==3.10
      - matplotlib==3.10.8
      - mink==0.0.5
      - mujoco==3.4.0
      - numba==0.63.1
      - opencv-python==4.11.0.86
      - pluggy==1.6.0
      - protobuf==6.33.4
      - pynput==1.8.1
      - pyopengl==3.1.10
      - pyparsing==3.3.1
      - pytest==9.0.2
      - python-xlib==0.33
      - qpsolvers==4.8.2
      - quadprog==0.1.13
      - regex==2026.1.15
      - safetensors==0.7.0
      - scipy==1.15.3
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - termcolor==3.3.0
      - tokenizers==0.19.1
      - tomli==2.4.0
      - tqdm==4.67.1
      - transformers==4.41.2
      - werkzeug==3.1.5
      - zipp==3.23.0
prefix: /scratch/gilbreth/zoellner/conda/envs/guided_diffusion
